const PokemonActionTypes = {
  REQUEST_POKEMON_PENDING: "REQUEST_POKEMON_PENDING",
  REQUEST_POKEMON_SUCCESS: "REQUEST_POKEMON_SUCCESS",
  REQUEST_POKEMON_FAILED: "REQUEST_POKEMON_FAILED"
};

export default PokemonActionTypes;
