const PokemonsActionTypes = {
  REQUEST_POKEMONS_PENDING: "REQUEST_POKEMONS_PENDING",
  REQUEST_POKEMONS_SUCCESS: "REQUEST_POKEMONS_SUCCESS",
  REQUEST_POKEMONS_FAILED: "REQUEST_POKEMONS_FAILED"
};

export default PokemonsActionTypes;
